<a href="https://colab.research.google.com/github/AISHIK1/NN-with-Pytorch/blob/main/dataloader_dataset_pytoch_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
from sklearn.datasets import make_classification
import torch

In [67]:
X,y=make_classification(
    n_samples=100,
    n_features=4,
    n_informative=2,
    n_redundant=0,
    random_state=1,
    n_classes=2
)

In [68]:
X.shape

(100, 4)

In [69]:
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [70]:
from torch.utils.data import Dataset,DataLoader

In [71]:
class customDataset(Dataset):

  def __init__(self,labels,features):
    self.features=features
    self.labels=labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self,index):

    return self.features[index],self.labels[index]

In [72]:
dataset=customDataset(X,y)

In [73]:
len(dataset)

100

In [74]:
dataset[0]

(tensor(0), tensor([-1.3966, -1.0141, -0.0019, -0.9571]))

In [75]:
dataloader=DataLoader(dataset,batch_size=4,shuffle=True)

In [76]:
for batch_features,batch_label in dataloader:
  print(batch_features)
  print(batch_label)
  print('-'*50)

tensor([1, 0, 0, 1])
tensor([[-0.1755, -0.4463, -0.1160,  0.4813],
        [-0.6070, -1.1805,  0.4295, -0.9554],
        [-0.6180,  0.2595,  1.4514, -1.2722],
        [-0.5330,  1.0446, -0.9339,  0.8589]])
--------------------------------------------------
tensor([0, 1, 0, 0])
tensor([[-0.0512,  1.6609,  0.6546, -0.8452],
        [ 0.7848, -1.1248,  0.4173,  0.8170],
        [ 0.0085,  0.3836, -0.1100, -1.1895],
        [ 0.9392,  1.6050, -0.5575, -0.7910]])
--------------------------------------------------
tensor([1, 0, 0, 0])
tensor([[-0.8678, -1.0690, -0.8773,  0.6770],
        [-1.3057, -1.4936,  1.8105, -0.7607],
        [ 0.1291, -1.1553,  1.4075, -1.0808],
        [-0.7333, -1.0663,  0.2765,  0.8230]])
--------------------------------------------------
tensor([0, 1, 1, 1])
tensor([[ 0.6747, -1.6397, -0.8613, -0.7157],
        [-0.2974, -0.9080, -0.0845,  1.1130],
        [ 0.5644,  1.6241,  1.8347,  0.4823],
        [ 1.7680,  0.2873, -1.4266,  0.6338]])
-----------------------

In [77]:
#using the samedataset again

import os

os.environ['KAGGLE_USERNAME'] = 'aishik996'
os.environ['KAGGLE_API_TOKEN'] = 'KGAT_61236d6a08ac73ba31896583260ad688'


In [78]:
!kaggle datasets download -d uciml/breast-cancer-wisconsin-data

Dataset URL: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data
License(s): CC-BY-NC-SA-4.0
breast-cancer-wisconsin-data.zip: Skipping, found more recently modified local copy (use --force to force download)


In [79]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder


In [80]:
import zipfile

with zipfile.ZipFile('breast-cancer-wisconsin-data.zip', 'r') as zip_ref:
    zip_ref.extractall()


In [81]:
df=pd.read_csv('data.csv')

df.drop(columns=['Unnamed: 32','id'],inplace=True)

X=df.drop(columns=['diagnosis'])
y=df['diagnosis']


X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


In [82]:
sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


le=LabelEncoder()

y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)


X_train=torch.from_numpy(X_train)
X_test=torch.from_numpy(X_test)
y_train=torch.from_numpy(y_train)
y_test=torch.from_numpy(y_test)

In [83]:
X_train.float()
X_test.float()
y_train.float()
y_test.float()

tensor([0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
        0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1.,
        0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
        0., 0., 1., 0., 0., 1.])

In [84]:
from torch.utils.data import Dataset,DataLoader

In [85]:
class mydataset(Dataset):

  def __init__(self,features,labels):

    self.features=features
    self.labels=labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self,index):

    return self.features[index],self.labels[index]

In [86]:
train_dataset=mydataset(X_train,y_train)
test_dataset=mydataset(X_test,y_test)

In [87]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

In [88]:
import torch.nn as nn

class mynn(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )

  def forward(self,features):

    out=self.network(features)

    return out

In [92]:
learning_rate=0.1
epochs=25

model=mynn(X_test.shape[1])

loss_function=nn.BCELoss()

optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

In [113]:
for epoch in range(epochs):

  for batch_features,batch_label in train_loader:

    y_pred=model(batch_features.float())

    loss=loss_function(y_pred,batch_label.view(-1,1).float())

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    print(f'epochs :{epoch+1}  --- loss: {loss.item()}')

  print('-'*50)



epochs :1  --- loss: 0.05676945298910141
epochs :1  --- loss: 0.30213412642478943
epochs :1  --- loss: 0.035471025854349136
epochs :1  --- loss: 0.031831275671720505
epochs :1  --- loss: 0.05127875506877899
epochs :1  --- loss: 0.044882696121931076
epochs :1  --- loss: 0.04154784977436066
epochs :1  --- loss: 0.08297479897737503
epochs :1  --- loss: 0.04839291051030159
epochs :1  --- loss: 0.035572852939367294
epochs :1  --- loss: 0.057028524577617645
epochs :1  --- loss: 0.030529702082276344
epochs :1  --- loss: 0.04745693877339363
epochs :1  --- loss: 0.1381901204586029
epochs :1  --- loss: 0.029914187267422676
--------------------------------------------------
epochs :2  --- loss: 0.2226962149143219
epochs :2  --- loss: 0.06484849005937576
epochs :2  --- loss: 0.03581761196255684
epochs :2  --- loss: 0.05278444662690163
epochs :2  --- loss: 0.07186722010374069
epochs :2  --- loss: 0.05459163710474968
epochs :2  --- loss: 0.05359082296490669
epochs :2  --- loss: 0.049411412328481674


In [114]:
#evaluation

model.eval()  #setting the model to evaluation mode
accuracy=[]


with torch.no_grad():
  for batch_features,batch_label in test_loader:

    y_pred=model(batch_features.float())

    y_pred=(y_pred>0.5).float()

    batch_accuracy=(y_pred.view(-1)==batch_label).float().mean()

    accuracy.append(batch_accuracy.item())

overall_accuracy=sum(accuracy)/len(accuracy)

print(overall_accuracy)

0.9921875
