<a href="https://colab.research.google.com/github/AISHIK1/NN-with-Pytorch/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch.nn as nn

In [4]:
#creating model class

class Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):

    out=self.linear(features)
    out=self.sigmoid(out)

    return out

In [6]:
#create dataset

features=torch.rand(10,5)

model=Model(features.shape[1])

model(features)

tensor([[0.3656],
        [0.2937],
        [0.3236],
        [0.3370],
        [0.3573],
        [0.3449],
        [0.3240],
        [0.3302],
        [0.3486],
        [0.3517]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear.weight

Parameter containing:
tensor([[-0.1366, -0.3017,  0.1514, -0.1373, -0.1042]], requires_grad=True)

In [10]:
model.linear.bias

Parameter containing:
tensor([-0.3886], requires_grad=True)

In [13]:
from torchinfo import summary

summary(model,input_size=(10,5))6

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [29]:
#making 3 layers model


class Model2(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):

    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.relu(out)
    out=self.sigmoid(out)


    return out

In [30]:
features=torch.rand(10,5)

model=Model2(features.shape[1])

model(features)

tensor([[0.6331],
        [0.6332],
        [0.6332],
        [0.6327],
        [0.6324],
        [0.6332],
        [0.6286],
        [0.6317],
        [0.6407],
        [0.6283]], grad_fn=<SigmoidBackward0>)

In [33]:
summary(model,input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─ReLU: 1-4                              [10, 1]                   --
├─Sigmoid: 1-5                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [35]:
#using Sequntial container


class Model3(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )


  def forward(self,features):

    out=self.network(features)


    return out


In [36]:
features=torch.rand(10,5)

model=Model3(features.shape[1])

model.forward(features)

tensor([[0.3810],
        [0.3246],
        [0.3231],
        [0.3349],
        [0.3482],
        [0.3534],
        [0.3041],
        [0.3357],
        [0.3594],
        [0.3563]], grad_fn=<SigmoidBackward0>)

In [37]:
#using the previous dataset

import os

os.environ['KAGGLE_USERNAME'] = 'aishik996'
os.environ['KAGGLE_API_TOKEN'] = 'KGAT_61236d6a08ac73ba31896583260ad688'

In [38]:
!kaggle datasets download -d uciml/breast-cancer-wisconsin-data

Dataset URL: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data
License(s): CC-BY-NC-SA-4.0
100% 48.6k/48.6k [00:00<00:00, 1.13MB/s]



In [39]:
import zipfile

with zipfile.ZipFile('breast-cancer-wisconsin-data.zip', 'r') as zip_ref:
    zip_ref.extractall()


In [40]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder


In [41]:

df=pd.read_csv('data.csv')

In [42]:
df.drop(columns=['Unnamed: 32','id'],inplace=True)

In [43]:
X=df.drop(columns=['diagnosis'])
y=df['diagnosis']

In [44]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [45]:

sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


le=LabelEncoder()

y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)

In [62]:
X_train=torch.from_numpy(X_train)
X_test=torch.from_numpy(X_test)
y_train=torch.from_numpy(y_train)
y_test=torch.from_numpy(y_test)

TypeError: expected np.ndarray (got Tensor)

In [63]:
X_train.float()
X_test.float()
y_train.float()
y_test.float()

tensor([0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
        0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1.,
        0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
        0., 0., 1., 0., 0., 1.])

In [75]:
class Model4(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self,features):

    out=self.linear(features)
    out=self.sigmoid(out)

    return out

  def loss(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    loss=-(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
    return loss

In [74]:
learing_rate=0.1
epochs=25
model=Model4(X_train.shape[1])


for i in range(epochs):
  y_pred=model(X_train.float())
  loss=model.loss(y_pred,y_train)

  loss.backward()

  with torch.no_grad():
    model.linear.weight-=learing_rate*model.linear.weight.grad
    model.linear.bias-=learing_rate*model.linear.bias.grad

  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  print(f'epoch : {i+1}, loss : {loss}')

epoch : 1, loss : 0.7080625891685486
epoch : 2, loss : 0.7015595436096191
epoch : 3, loss : 0.6971961259841919
epoch : 4, loss : 0.6940234899520874
epoch : 5, loss : 0.6915311217308044
epoch : 6, loss : 0.6894506216049194
epoch : 7, loss : 0.6876399517059326
epoch : 8, loss : 0.6860216856002808
epoch : 9, loss : 0.6845508813858032
epoch : 10, loss : 0.6831998825073242
epoch : 11, loss : 0.6819503307342529
epoch : 12, loss : 0.6807889342308044
epoch : 13, loss : 0.6797056794166565
epoch : 14, loss : 0.6786926984786987
epoch : 15, loss : 0.6777436137199402
epoch : 16, loss : 0.6768526434898376
epoch : 17, loss : 0.6760151982307434
epoch : 18, loss : 0.6752271056175232
epoch : 19, loss : 0.6744847893714905
epoch : 20, loss : 0.6737848520278931
epoch : 21, loss : 0.6731244921684265
epoch : 22, loss : 0.6725009083747864
epoch : 23, loss : 0.6719117760658264
epoch : 24, loss : 0.6713548302650452
epoch : 25, loss : 0.670828104019165


In [78]:
#changing to loss function libaray in nn module

learing_rate=0.1
epochs=25
model2=Model4(X_train.shape[1])
loss_function=nn.BCELoss()

for i in range(epochs):
  y_pred=model2(X_train.float())
  loss=loss_function(y_pred,y_train.view(-1,1).float())

  loss.backward()

  with torch.no_grad():
    model2.linear.weight-=learing_rate*model2.linear.weight.grad
    model.linear.bias-=learing_rate*model2.linear.bias.grad

  model2.linear.weight.grad.zero_()
  model2.linear.bias.grad.zero_()

  print(f'epoch : {i+1}, loss : {loss}')

epoch : 1, loss : 0.5681450366973877
epoch : 2, loss : 0.4705345630645752
epoch : 3, loss : 0.4111654758453369
epoch : 4, loss : 0.3706437051296234
epoch : 5, loss : 0.34085145592689514
epoch : 6, loss : 0.31780052185058594
epoch : 7, loss : 0.29929301142692566
epoch : 8, loss : 0.2840123474597931
epoch : 9, loss : 0.27111849188804626
epoch : 10, loss : 0.2600483298301697
epoch : 11, loss : 0.25040873885154724
epoch : 12, loss : 0.24191632866859436
epoch : 13, loss : 0.23436084389686584
epoch : 14, loss : 0.22758270800113678
epoch : 15, loss : 0.22145821154117584
epoch : 16, loss : 0.21588987112045288
epoch : 17, loss : 0.2107994258403778
epoch : 18, loss : 0.2061235010623932
epoch : 19, loss : 0.2018098384141922
epoch : 20, loss : 0.1978149563074112
epoch : 21, loss : 0.1941024214029312
epoch : 22, loss : 0.19064132869243622
epoch : 23, loss : 0.18740525841712952
epoch : 24, loss : 0.18437153100967407
epoch : 25, loss : 0.18152038753032684


In [83]:
with torch.no_grad():
  y_pred=model2(X_test.float())
  y_pred=(y_pred>0.6).float()

  accuracy=(y_pred==y_test).float().mean()
  print(accuracy)

tensor(0.5345)


In [87]:
#using optimizers


learing_rate=0.1
epochs=25
model3=Model4(X_train.shape[1])

optimizer=torch.optim.SGD(model.parameters(),lr=learing_rate)

for i in range(epochs):
  y_pred=model3(X_train.float())
  loss=model3.loss(y_pred,y_train)

  optimizer.zero_grad()

  loss.backward()

  optimizer.step()


  print(f'epoch : {i+1}, loss : {loss}')

epoch : 1, loss : 0.727583110332489
epoch : 2, loss : 0.727583110332489
epoch : 3, loss : 0.727583110332489
epoch : 4, loss : 0.727583110332489
epoch : 5, loss : 0.727583110332489
epoch : 6, loss : 0.727583110332489
epoch : 7, loss : 0.727583110332489
epoch : 8, loss : 0.727583110332489
epoch : 9, loss : 0.727583110332489
epoch : 10, loss : 0.727583110332489
epoch : 11, loss : 0.727583110332489
epoch : 12, loss : 0.727583110332489
epoch : 13, loss : 0.727583110332489
epoch : 14, loss : 0.727583110332489
epoch : 15, loss : 0.727583110332489
epoch : 16, loss : 0.727583110332489
epoch : 17, loss : 0.727583110332489
epoch : 18, loss : 0.727583110332489
epoch : 19, loss : 0.727583110332489
epoch : 20, loss : 0.727583110332489
epoch : 21, loss : 0.727583110332489
epoch : 22, loss : 0.727583110332489
epoch : 23, loss : 0.727583110332489
epoch : 24, loss : 0.727583110332489
epoch : 25, loss : 0.727583110332489


In [88]:
with torch.no_grad():
  y_pred=model3(X_test.float())
  y_pred=(y_pred>0.6).float()

  accuracy=(y_pred==y_test).float().mean()

print(accuracy)

tensor(0.5883)
